### ISSUE TITLE
Add "opinionated" in the readme?

### ISSUE THREAD

**Issue by goyalyashpal** [franneck94/Vscode-Python-Config#1]
as there are lots of things which seem to be _not lightly_ opinionated....
many of which are not even related with development in python.

so, adding this word will make it clear as to what the expectation should be.

There's nothing wrong with configs being this way, i just think saying it upfront will be awesome.

So: 

```diff
- Creates config files for modern Python projects.   
+ Creates opinionated config files for modern Python projects.   
```

https://github.com/franneck94/Vscode-Python-Config/blob/0ab6888ff941573aafd89e9eed58ce9713be9875/README.md#L3

**Comment by franneck94** [comment]
Done.
